pollme/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace="accounts"))
]

polls/urls.py
from django.urls import path

from . import views

app_name="polls"
urlpatterns = [
    path('list/', views.polls_list, name="list"),
    path('add/', views.add_poll, name='add'),
    path('edit/<int:poll_id>/', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name="add_choice"),
    path('edit/choice/<int:choice_id>/', views.edit_choice, name="edit_choice"),
    path('delete/choice/<int:choice_id>/', views.delete_choice, name='choice_confirm_delete'),
    path('delete/poll/<int:poll_id>/', views.delete_poll, name='poll_confirm_delete'),
    # polls/details/1/
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    # polls/details/1/vote
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')
]

polls/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Poll(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    text = models.CharField(max_length=255)
    pub_date = models.DateField()

    def __str__(self):
        return self.text

    def user_can_vote(self, user):
        """
        Returns False is user has already voted, else True
        """
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

    @property
    def num_votes(self):
        return self.vote_set.count()

    def get_results_dict(self):
        """
        Returns a list of objects in the form:
        [
            # for each related choice
            {
                'text': choice_text,
                'num_votes': number of votes on that choice
                'percentage': num_votes / poll.num_votes * 100
            }
        ]
        """
        res = []
        for choice in self.choice_set.all():
            d = {}
            d['text'] = choice.choice_text
            d['num_votes'] = choice.num_votes
            if not self.num_votes:
                d['percentage'] = 0
            else:
                d['percentage'] = choice.num_votes / self.num_votes * 100
            res.append(d)
        return res


class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    def __str__(self):
        return "{} - {}".format(self.poll.text[:25], self.choice_text[:25])

    @property
    def num_votes(self):
        return self.vote_set.count()

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

polls/forms.py
from django import forms

from .models import Choice, Poll

class PollForm(forms.ModelForm):

    choice1 = forms.CharField(
                        label='First Choice',
                        max_length=100,
                        min_length=3,
                        widget=forms.TextInput(attrs={'class': 'form-control'}))
    choice2 = forms.CharField(
                        label='Second Choice',
                        max_length=100,
                        min_length=3,
                        widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Poll
        fields = ['text', 'choice1', 'choice2']
        widgets = {
            'text': forms.Textarea(attrs={"class":"form-control", "rows": 5, "cols": 20})
        }

class EditPollForm(forms.ModelForm):

    class Meta:
        model = Poll
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={"class":"form-control", "rows": 5, "cols": 20})
        }

class ChoiceForm(forms.ModelForm):

    class Meta:
        model = Choice
        fields = ['choice_text']

polls/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .models import Choice, Poll, Vote

from .forms import PollForm, EditPollForm, ChoiceForm

# Create your views here.
@login_required
def polls_list(request):
    """
    Renders the polls_list.html template which lists all the
    currently available polls
    """
    polls = Poll.objects.all()
    search_term=''

    if 'text' in request.GET:
        polls = polls.order_by('text')

    if 'pub_date' in request.GET:
        polls = polls.order_by('-pub_date')

    if 'num_votes' in request.GET:
        polls = polls.annotate(Count('vote')).order_by('-vote__count')

    if 'search' in request.GET:
        search_term = request.GET['search']
        polls = polls.filter(text__icontains=search_term)

    paginator = Paginator(polls, 5)

    page = request.GET.get('page')
    polls = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()

    context = {'polls': polls, 'params': params, 'search_term': search_term}
    return render(request, 'polls/polls_list.html', context)

@login_required
def add_poll(request):
    if request.method == "POST":
        form = PollForm(request.POST)
        if form.is_valid():
            new_poll = form.save(commit=False)
            new_poll.pub_date = datetime.datetime.now()
            new_poll.owner = request.user
            new_poll.save()
            new_choice1 = Choice(
                                    poll = new_poll,
                                    choice_text=form.cleaned_data['choice1']
                                ).save()
            new_choice2 = Choice(
                                    poll = new_poll,
                                    choice_text=form.cleaned_data['choice2']
                                ).save()
            messages.success(
                            request,
                            'Poll and Choices added!',
                            extra_tags='alert alert-success alert-dismissible fade show'
                            )
            return redirect('polls:list')
    else:
        form = PollForm()
    context = {'form': form}
    return render(request, 'polls/add_poll.html', context)

@login_required
def delete_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
        poll.delete()
        messages.success(
                        request,
                        'Poll Deleted Successfully',
                        extra_tags='alert alert-success alert-dismissible fade show'
                        )
        return redirect('polls:list')

    return render(request, 'polls/delete_poll_confirm.html', {'poll':poll})

@login_required
def edit_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
        form = EditPollForm(request.POST, instance=poll)
        if form.is_valid():
            form.save()
            messages.success(
                            request,
                            'Poll Edit Successfully',
                            extra_tags='alert alert-success alert-dismissible fade show'
                            )
            return redirect('polls:list')
    else:
        form = EditPollForm(instance=poll)

    return render(request, 'polls/edit_poll.html', {'form': form, 'poll':poll})

@login_required
def add_choice(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
        form = ChoiceForm(request.POST)
        if form.is_valid():
            new_choice = form.save(commit=False)
            new_choice.poll = poll
            new_choice.save()
            messages.success(
                            request,
                            'Choice Added Successfully',
                            extra_tags='alert alert-success alert-dismissible fade show'
                            )
            return redirect('polls:list')
    else:
        form = ChoiceForm()
    return render(request, 'polls/add_choice.html', {'form':form})

@login_required
def edit_choice(request, choice_id):
    choice = get_object_or_404(Choice, id=choice_id)
    poll = get_object_or_404(Poll, id=choice.poll.id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
        form = ChoiceForm(request.POST, instance=choice)
        if form.is_valid():
            form.save()
            messages.success(
                            request,
                            'Choice Edited Successfully',
                            extra_tags='alert alert-success alert-dismissible fade show'
                            )
            return redirect('polls:list')
    else:
        form = ChoiceForm(instance=choice)
    return render(request, 'polls/add_choice.html', {'form':form, 'edit_mode': True, 'choice':choice})

@login_required
def delete_choice(request, choice_id):
    choice = get_object_or_404(Choice, id=choice_id)
    poll = get_object_or_404(Poll, id=choice.poll.id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
        choice.delete()
        messages.success(
                        request,
                        'Choice Deleted Successfully',
                        extra_tags='alert alert-success alert-dismissible fade show'
                        )
        return redirect('polls:list')

    return render(request, 'polls/delete_choice_confirm.html', {'choice':choice})

@login_required
def poll_detail(request, poll_id):
    """
    Render the poll_detail.html template which allows a user to vote
    on the choices of a poll
    """
    # poll = Poll.objects.get(id=poll_id)
    poll = get_object_or_404(Poll, id=poll_id)
    user_can_vote = poll.user_can_vote(request.user)
    results = poll.get_results_dict()
    context = {'poll': poll, 'user_can_vote': user_can_vote, 'results': results}
    return render(request, 'polls/poll_detail.html', context)

@login_required
def poll_vote(request, poll_id):
    # try:
    poll = get_object_or_404(Poll, id=poll_id)

    if not poll.user_can_vote(request.user):
        messages.error(request, 'Are you crazy? You have already voted on this poll!')
        return redirect('polls:detail', poll_id=poll_id)

    choice_id = request.POST.get('choice')
    if choice_id:
        choice = Choice.objects.get(id=choice_id)
        new_vote = Vote(user=request.user, poll=poll, choice=choice)
        new_vote.save()
    else:
        messages.error(request, 'No Choice Was Found!')
        return redirect('polls:detail', poll_id=poll_id)
    return redirect('polls:detail', poll_id=poll_id)

polls/templates/polls/add_choice.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h1 class='text-center'>
      {% if edit_mode %}
        Edit The Choice
      {% else %}
        Add A New Choice
      {% endif %}
      Using The Form Below
  </h1>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="submit" class='btn btn-primary'>
        {% if edit_mode %}
          <a href="{% url 'polls:choice_confirm_delete' choice.id %}"
              class='btn btn-danger'>
              <i class="far fa-trash-alt"></i> Delete
          </a>
        {% endif %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

polls/templates/polls/add_poll.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h1 class='text-center'>Add Poll Using Form Below</h1>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="submit" class='btn btn-primary'>
      </form>
    </div>
  </div>
</div>

{% endblock %}

polls/templates/polls/delete_choice_confirm.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <input type='submit' class='btn btn-danger' value='I hope you know what you what you are doing!'>
</form>

{% endblock %}

polls/templates/polls/delete_poll_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 text-center">
      <form action="" method="post">
        {% csrf_token %}
        <input type='submit' class='btn btn-danger' value='Do you want to delete this poll?'>
      </form>
    </div>
  </div>
</div>

{% endblock %}

polls/templates/polls/edit_poll.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h1 class='text-center'>Edit Poll Using Form Below</h1>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit" value="submit" class='btn btn-primary'>
        <a href="{% url 'polls:add_choice' poll.id %}" class='btn btn-warning'>Add Choice</a>
        <a href="{% url 'polls:poll_confirm_delete' poll.id %}"
            class='btn btn-danger'>
            <i class="far fa-trash-alt"></i> Delete
        </a>
      </form>

    <h3 class='text-center'>Choices</h3>
    {% for choice in poll.choice_set.all %}
      <p><a href="{% url 'polls:edit_choice' choice.id %}"><i class="fas fa-pencil-alt"></i></a> {{choice.choice_text}}</p>
    {% endfor %}

    </div>
  </div>
</div>

{% endblock %}

polls/templates/polls/poll_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

<p>{{poll}} - {{poll.num_votes}} votes</p>

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}

{% for choice in poll.choice_set.all %}

  <input type="radio"
         name="choice"
         id="choice{{ forloop.counter }}"
         value="{{choice.id}}"/>
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} - {{ choice.num_votes }}</label>
  <br/>

{% endfor %}
<input class='btn btn-primary mb-2' type="submit" value="Vote" {% if not user_can_vote %}disabled{% endif %}/>

</form>

{% if not user_can_vote %}

    {% for choice_dict in results %}
    <div class="row">
        <div class="col-sm-6">
        {{choice_dict.text}}
        <div class="progress mb-1">
          <div class="progress-bar" role="progressbar" style="width: {{choice_dict.percentage}}%;">{{choice_dict.num_votes}}</div>
        </div>
      </div>
    </div>
    {% endfor %}

{% else %}
  <p>Vote to see results!</p>
{% endif %}

</div>
{% endblock %}

polls/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1 class='text-center'>Welcome to Poll List!</h1>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">

      {% if messages %}
          {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
             </button>
          </div>
          {% endfor %}
      {% endif %}

      <a
          href="?text=True"
          class="btn btn-{% if 'text' in request.GET %}warning{% else %}primary{% endif %}"
          style="margin-bottom: 5px">Text
      </a>
      <a
          href="?pub_date=True"
          class="btn btn-{% if 'pub_date' in request.GET %}warning{% else %}primary{% endif %}"
          style="margin-bottom: 5px">Pub_date
      </a>
      <a
          href="?num_votes=True"
          class="btn btn-{% if 'num_votes' in request.GET %}warning{% else %}primary{% endif %}"
          style="margin-bottom: 5px">Num_votes
      </a>
      <a href="{% url 'polls:add' %}" class="btn btn-primary" style="margin-bottom: 5px">Add <i class="fas fa-plus"></i> </a>

      <form class="form-inline my-2 my-lg-1">
        <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Search"
            aria-label="Search"
            name='search'
            value="{{search_term}}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

      <ul class="list-group">
        {% for poll in polls %}
        <li class="list-group-item">
          <a href="{% url 'polls:detail' poll.id %}">{{ poll }}</a>
          {% if request.user == poll.owner %}
            <a href="{% url 'polls:edit_poll' poll.id %}" class='float-right'><i class="fas fa-pencil-alt"></i></a>
          {% endif %}
        </li>
        {% endfor %}
      </ul>

      <div class="pagination">
          <span class="step-links">
              {% if polls.has_previous %}
                  <a href="?page=1&{{params}}">&laquo; first</a>
                  <a href="?page={{ polls.previous_page_number }}&{{params}}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ polls.number }} of {{ polls.paginator.num_pages }}.
              </span>

              {% if polls.has_next %}
                  <a href="?page={{ polls.next_page_number }}&{{params}}">next</a>
                  <a href="?page={{ polls.paginator.num_pages }}&{{params}}">last &raquo;</a>
              {% endif %}
          </span>
      </div>

    </div>
  </div>
</div>
{% endblock %}