accounts/urls.py
from django.urls import path

from . import views

app_name="accounts"
urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.user_registration, name="register")
]

pollme/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace="accounts"))
]

polls/urls.py
from django.urls import path

from . import views

app_name="polls"
urlpatterns = [
    path('list/', views.polls_list, name="list"),
    path('add/', views.add_poll, name='add'),
    path('edit/<int:poll_id>/', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/choice/add/', views.add_choice, name="add_choice"),
    path('edit/choice/<int:choice_id>/', views.edit_choice, name="edit_choice"),
    path('delete/choice/<int:choice_id>/', views.delete_choice, name='choice_confirm_delete'),
    path('delete/poll/<int:poll_id>/', views.delete_poll, name='poll_confirm_delete'),
    # polls/details/1/
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    # polls/details/1/vote
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'polls:list' %}">Polls</a>
    </div>
    <div class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>